### ISSUE TITLE
No valid partitions found. Exiting.

### ISSUE THREAD

**Issue by bingyu50** [mayankk2308/kryptonite#1]
=== Kryptonite Configurator 0.9.0 ===

This tool can prepare a disk for a simplified OpenCore
configuration for your Mac to run Kryptonite.

If you have already configured a bootloader,
this tool can provide you the necessary resources
to enable eGPUs with your existing bootloader.

Populating disks...
Total valid partitions found: 0

>> Detected Volumes

No valid partitions found. Exiting.

**Comment by mayankk2308** [comment]
Add a partition manually via Disk Utility as mentioned in the installation section: https://github.com/mayankk2308/kryptonite#installation

**Comment by mayankk2308** [comment]
The installation instructions on the main page have been updated to better communicate the requirements. Please read through those. With respect to APFS/resizing - those features may be added later and will be tracked under the **missing-features** label, thanks.
