### ISSUE TITLE
Nvidia EGPU not detected in MacOSX 

### ISSUE THREAD

**Issue by limyuxuan2** [mayankk2308/kryptonite#11]
### Problem Description
I've followed all the instructions and installed it but upon booting my GTX1080 Aorus EGPU is not detected in the devices and doesn't appear in the menu bar. 
[opencore-2021-07-30-083130.txt](https://github.com/mayankk2308/kryptonite/files/6923084/opencore-2021-07-30-083130.txt)

### Logs
Generate logs via **Kryptonite Configurator** or follow this wiki. 
[opencore-2021-08-03-092213.txt](https://github.com/mayankk2308/kryptonite/files/6923081/opencore-2021-08-03-092213.txt)
[opencore-2021-07-26-130343.txt](https://github.com/mayankk2308/kryptonite/files/6923083/opencore-2021-07-26-130343.txt)

**Comment by Piipperi** [comment]
NVIDIA GPUs (except for Kepler ones) are NOT supported on 10.14 and above.

**Comment by mayankk2308** [comment]
Based on your logs, I can see kernel version `17.7.0` being loaded. Can you confirm you are running High Sierra (macOS 10.13.6)? If so, all you probably need is to install the NVIDIA Web Drivers. Please install web drivers and try again: https://github.com/Benjamin-Dobell/nvidia-update

**Comment by limyuxuan2** [comment]
Hey there I've already run the web driver installer and it said that I've already have the latest version. The egpu still does not appear in the menu bar and in the system info graphics display section it simply appears as "display"
With the following details:
Type:	External GPU
  Bus:	PCIe
  PCIe Lane Width:	x4
  VRAM (Dynamic, Max):	
  Vendor:	NVIDIA (0x10de)
  Device ID:	0x1b80
  Revision ID:	0x00a1
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.20 [3.2.8]
  Kernel Extension Info:	No Kext Loaded

**Comment by mayankk2308** [comment]
I’ll need logs from the Lilu kext to debug further (see README). Please also share your EFI folder (zip it and upload here) Additionally I would recommend trying hot-plugging the egpu after booting into macOS then check what happens.

**Comment by mdir** [comment]
Try with bootcamp if it works with bootcamp and Win10

**Comment by mayankk2308** [comment]
Still awaiting logs. Will close issue soon.

**Comment by mayankk2308** [comment]
No logs provided.
