### ISSUE TITLE
Can't boot from SD Card or USB

### ISSUE THREAD

**Issue by ethaniel** [mayankk2308/kryptonite#14]
### Problem Description
1. I have an older Macbook Pro 2015 with a SD Card reader.
2. I was hoping to repartition it and set the first partition as FAT and put Kryptonite on it with the help of the installer.
3. Install completes successfully, however when I restart my Macbook with the "Option" pressed, I don't see the SD Card as a possible boot method (I only the see the main hard drive).
4. Same problem persists with a separate dedicated USB flash drive.

**Comment by mayankk2308** [comment]
Unfortunately SD card is not supported as boot drive. I don't know why a dedicated USB drive did not work for you though. Did you set up the USB device via the installer as well?

**Comment by mayankk2308** [comment]
Closing until user provides further information. No other reports of problems received with respect to USB drive.
