### ISSUE TITLE
No FileVault View on Boot

### ISSUE THREAD

**Issue by eggicusroundplumpius** [mayankk2308/kryptonite#16]
### Problem Description

I'm not sure if this is normal behaviour, but if I have only the eGPU and its monitors connected it will not show anything on screen when booting to macOS through FileVault. It should take me to a password entry screen, but it doesn't. Only by connecting to one of the internal GPUs do I get anything before it's fully booted to desktop. Furthermore, that display has to be connected before the system is powered up at all or it won't show on that one either.

I'm using a 2013 Mac Pro with a BlackMagic eGPU Pro. I've also got OpenCore set to skip the boot picker.

### Logs
I couldn't quite wrap my head around how to create the logs. Apparently I need to use a debug variant of OpenCore or something and I have to reinstall the whole thing? I couldn't find where to get the debug version, so if logs are needed I'm afraid I'm going to need some assistance.

**Comment by mayankk2308** [comment]
Boot screen (FileVault login) is not supported via egpu connected displays.

For logs, follow the README/script.
