### ISSUE TITLE
Native 5K resolution unavailable on iMac when booted via OpenCore

### ISSUE THREAD

**Issue by Rohmister** [mayankk2308/kryptonite#17]
### Problem Description
i have an issue with kryptonite don't put native 5k resolution . But with Purge Wrangler all good. 
### Logs
Generate logs via **Kryptonite Configurator** or follow this wiki.

**Comment by mayankk2308** [comment]
Please provide macOS version and copy of your config.plist file. Also provide screenshot of screen resolution selection screen.

**Comment by Rohmister** [comment]
hello, im using macOS 11.6 with 5120 x 2880 resolution. With Kryptonite resolution scale to 2560 x 1600 (sorry don't have screenshot i've re-install Purge wrangler yesterday after that. But I've preserve my conflit plist
[config.plist.zip](https://github.com/mayankk2308/kryptonite/files/7252131/config.plist.zip)
.

**Comment by mayankk2308** [comment]
@Rohmister this seems to be a problem with OpenCore: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/359

Currently there doesn't seem to be a solution.

**Comment by Rohmister** [comment]
@mayankk2308 thanks for the answer. I'll stay with Purge Wrangler for now until open core fix the problem. Did you know if your Purge wrangler will work for the next macOS?

**Comment by mayankk2308** [comment]
@Rohmister unless said otherwise, PurgeWrangler should continue working. Always check it's wiki for most up-to-date information. I will also update this issue in case a solution for 5K iMacs is discovered. Leaving open.

**Comment by mayankk2308** [comment]
@Rohmister In config.plist, you should see **OpenRuntime.efi**. Can you disable this and try?

**Comment by Rohmister** [comment]
@mayankk2308 , sorry I've don't see before I was in travel. I'll try this tomorrow .

**Comment by mayankk2308** [comment]
I won’t be integrating that patchset into Kryptonite directly as it spoofs virtualization on native macs. Given that modern macOS doesn’t support any older TB1/2 devices anyway, most people will use OCLP anyway, and can then install just the Kryptonite kext to their existing OCLP install.
