### ISSUE TITLE
No Kryptonite in bootliader

### ISSUE THREAD

**Issue by iraklyshanidze** [mayankk2308/kryptonite#18]
### Problem Description

I followed the instructions (fresh reinstall of macOS 11.6, created a partition on an internal SSD, and ran Kryptonite setup), but upon restart, there is only MackintoshHD in the bootloader. Not sure if enabling logs will help, as there is nothing to generate logs from is loaded.

### Logs
Generate logs via **Kryptonite Configurator** or follow this wiki.

**Comment by mayankk2308** [comment]
@iraklyshanidze please re-create this issue using new bug report template: https://github.com/mayankk2308/kryptonite/issues/new/choose
