### ISSUE TITLE
[BUG] Easy install command does not work

### ISSUE THREAD

**Issue by Piipperi** [mayankk2308/kryptonite#19]
### What Mac are you using?

MacBook Pro 11,3

### What version of macOS are you using?

11.x

### Are you using OpenCore Legacy Patcher?

Yes

### What is your issue?

I'm getting 3 different errors when trying to execute the command.
First try, it gives this:
```
Epic-Gamer-MacBook:~ Piipperi$ curl -qLs $(curl -qLs "https://api.github.com/repos/mayankk2308/kryptonite/releases/latest" | grep '"browser_download_url":' | grep Installer | sed -E 's/.*"([^"]+)".*/\1/') > Installer.zip; ditto -x -k Installer.zip .; cd Installer; chmod +x installer.sh; ./installer.sh; cd ../; rm -rf Installer*
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
ditto: Couldn't read PKZip signature
-bash: cd: Installer: No such file or directory
chmod: installer.sh: No such file or directory
-bash: ./installer.sh: No such file or directory
Epic-Gamer-MacBook:Users Piipperi$ 
```

Second try:
```
Epic-Gamer-MacBook:Users Piipperi$ curl -qLs $(curl -qLs "https://api.github.com/repos/mayankk2308/kryptonite/releases/latest" | grep '"browser_download_url":' | grep Installer | sed -E 's/.*"([^"]+)".*/\1/') > Installer.zip; ditto -x -k Installer.zip .; cd Installer; chmod +x installer.sh; ./installer.sh; cd ../; rm -rf Installer*
-bash: Installer.zip: Permission denied
ditto: Installer.zip: No such file or directory
-bash: cd: Installer: No such file or directory
chmod: installer.sh: No such file or directory
-bash: ./installer.sh: No such file or directory
Epic-Gamer-MacBook:/ Piipperi$ 
```

And on the third try:
```
Epic-Gamer-MacBook:/ Piipperi$ curl -qLs $(curl -qLs "https://api.github.com/repos/mayankk2308/kryptonite/releases/latest" | grep '"browser_download_url":' | grep Installer | sed -E 's/.*"([^"]+)".*/\1/') > Installer.zip; ditto -x -k Installer.zip .; cd Installer; chmod +x installer.sh; ./installer.sh; cd ../; rm -rf Installer*
-bash: Installer.zip: Read-only file system
ditto: Installer.zip: No such file or directory
-bash: cd: Installer: No such file or directory
chmod: installer.sh: No such file or directory
-bash: ./installer.sh: No such file or directory
Epic-Gamer-MacBook:/ Piipperi$ 
```

And that Read-only file system error is where it's at after the 2nd try. It just gives that error when running the command. This "counter" resets when the Terminal is closed and re-opened.

SIP is disabled and I do have Homebrew, which is up to date. macOS version is 11.6.

### Upload Kryptonite Logs

Click here, then drag and drop your files in this area.

### Confirmation

- [ ] I have uploaded the OpenCore **config.plist**.
- [ ] I have uploaded all OpenCore Logs.
- [ ] I have uploaded Lilu logs.
- [x] I have explained my issue in detail.

**Comment by mayankk2308** [comment]
Where did you get this command? This is not the right command.

**Comment by Piipperi** [comment]
> Where did you get this command? This is not the right command.

From this Github repo's front page, aka the README.md

**Comment by mayankk2308** [comment]
Use the wiki. Looks like I overwrote the README which is the cause of this. I’ll fix.

**Comment by Piipperi** [comment]
> Use the wiki. Looks like I overwrote the README which is the cause of this. I’ll fix.

Alright, thanks
