### ISSUE TITLE
Installer formats incorrect volumes

### ISSUE THREAD

**Issue by pnoqable** [mayankk2308/kryptonite#2]
Installer formats wrong partition!!
I followed the steps of the "Installation" section of readme.md to create a fresh kryptonite partition on a usb thumb drive, entered the correct values, installer reported the correct values, but formated a completely wrong partition!! disk0s3 instead of disk2s1!!! (this deleted >200GB of downloads; Luckily no critical / system data and also i do have backups)

### Logs
> ➜  ~ curl -qLs $(curl -qs "https://api.github.com/repos/mayankk2308/kryptonite/releases/latest" | grep '"browser_download_url":' | grep ".sh" | sed -E 's/.*"([^"]+)".*/\1/') > k.sh; sh k.sh; rm k.sh
> k.sh: line 66: ((: 15 = 13 : attempted assignment to non-variable (error token is "= 13 ")
> Password:
> k.sh: line 66: ((: 15 = 13 : attempted assignment to non-variable (error token is "= 13 ")
> 
> === Kryptonite Configurator 0.9.0 ===
> 
> This tool can prepare a disk for a simplified OpenCore
> configuration for your Mac to run Kryptonite.
> 
> If you have already configured a bootloader,
> this tool can provide you the necessary resources
> to enable eGPUs with your existing bootloader.
> 
> Populating disks...
> Total valid partitions found: 3
> 
> >> Detected Volumes
> 
>   1. DATA
>   2. BOOTCAMP
>   3. OPENCORE
> 
>   R. Refresh
>   0. Quit
> 
> Note that APFS containers and volumes are not shown.
> If you want to use an internal volume, create a FAT32 partition
> via Disk Utility, after which it should show up here.
> 
> Choose disk to format: 3
> 
> Selected Disk: OPENCORE
> Disk Identifier: disk2s1
> 
> Formatting disk...
> Disk ready.
> 
> Installing Kryptonite...
> 
> If you want to emit logs for testing, please use
> DEBUG resources. Otherwise, press N to get RELEASE resources.
> 
> Downloading kryptonite resources...
> Download complete.
> Blessing disk...
> 
> Final boot-args: krygpu=NVDA krytbtv=2 -liludbg liludump=60 
> 
> If you have duplicate boot-args, consider fixing them manually.
> You can do this by editing config.plist on the bootloader disk.
> 
> Installation complete.
> 
> To use Kryptonite, press OPTION while booting
> and select the "Kryptonite" boot disk.
> ➜  ~ diskutil list
> /dev/disk0 (internal, physical):
>    #:                       TYPE NAME                    SIZE       IDENTIFIER
>    0:      GUID_partition_scheme                        *480.1 GB   disk0
>    1:                        EFI EFI                     209.7 MB   disk0s1
>    2:                 Apple_APFS Container disk1         128.0 GB   disk0s2
>    3:       Microsoft Basic Data KRYPTONITE              223.0 GB   disk0s3
>    4:       Microsoft Basic Data BOOTCAMP                128.9 GB   disk0s4
> 
> /dev/disk1 (synthesized):
>    #:                       TYPE NAME                    SIZE       IDENTIFIER
>    0:      APFS Container Scheme -                      +128.0 GB   disk1
>                                  Physical Store disk0s2
>    1:                APFS Volume MacOS                   11.3 GB    disk1s1
>    2:                APFS Volume Preboot                 82.2 MB    disk1s2
>    3:                APFS Volume Recovery                525.8 MB   disk1s3
>    4:                APFS Volume VM                      2.1 GB     disk1s4
>    5:                APFS Volume MacOS - Data            91.8 GB    disk1s5
> 
> /dev/disk2 (external, physical):
>    #:                       TYPE NAME                    SIZE       IDENTIFIER
>    0:     FDisk_partition_scheme                        *15.5 GB    disk2
>    1:                 DOS_FAT_32 OPENCORE                15.5 GB    disk2s1
> 
> ➜  ~ 
>

**Comment by pnoqable** [comment]
on my system this is 100% reproducible

**Comment by mayankk2308** [comment]
@pnoqable thanks for the report. I have removed installer from release section and changed instructions on the README to ensure others are not affected. I will investigate the issue and get back to you. At this time I don't yet have an idea as to why this happened. In your logs, the chosen disk identifier seems correct, yet the volume partitioned seems to be different and the `OPENCORE` volume still exists.

**Comment by pnoqable** [comment]
you sir are incredible: nice reaction time! :D 👍

**Comment by mayankk2308** [comment]
@pnoqable sorry for the inconvenience and apologies for the data loss. Luckily I was awake for this (5.30am here).

**Comment by mayankk2308** [comment]
I have found the bug and fixed the issue. Re-opening until the installer is rigorously tested.

**Comment by pnoqable** [comment]
:D I had exactly this question in mind, what time it might be on your location.. Lucky circumstances. Noworries: No real inconvenience or harm on my side; i'm glad that the report still came early enough that nobody else seemed to be affected. You can give me a new link to test against

**Comment by mayankk2308** [comment]
@pnoqable you can download the installer from the repo directly or paste this in a file: https://raw.githubusercontent.com/mayankk2308/kryptonite/main/Installer/kryptonite.sh

Then run the saved file as a script:
```shell
sh kryptonite.sh
```

**Comment by pnoqable** [comment]
fixed 👍

**Comment by pnoqable** [comment]
`➜  Downloads nano kryptonite.sh
➜  Downloads chmod +x kryptonite.sh 
➜  Downloads ./kryptonite.sh 
./kryptonite.sh: line 66: ((: 15 = 13 : attempted assignment to non-variable (error token is "= 13 ")
Password:
./kryptonite.sh: line 66: ((: 15 = 13 : attempted assignment to non-variable (error token is "= 13 ")

=== Kryptonite Configurator 1.0.0 ===

This tool can prepare a disk for a simplified OpenCore
configuration for your Mac to run Kryptonite.

If you have already configured a bootloader,
this tool can provide you the necessary resources
to enable eGPUs with your existing bootloader.

Populating disks...
Total valid partitions found: 3

>> Detected Volumes

  1. Data
  2. BOOTCAMP
  3. OPENCORE

  R. Refresh
  0. Quit

Note that APFS containers and volumes are not shown.
If you want to use an internal volume, create a FAT32 partition
via Disk Utility, after which it should show up here.

Choose disk to format: 3

Selected Disk: OPENCORE
Disk Identifier: disk2s1

Formatting disk (disk2s1)...
Disk ready.

Installing Kryptonite...

If you want to emit logs for testing, please use
DEBUG resources. Otherwise, press N to get RELEASE resources.

Downloading kryptonite resources...
Download complete.
Blessing disk...
Disk blessed.

Final boot-args: krygpu=NVDA krytbtv=2 -liludbg liludump=60 

If you have duplicate boot-args, consider fixing them manually.
You can do this by editing config.plist on the bootloader disk.

Installation complete.

To use Kryptonite, press OPTION while booting
and select the "Kryptonite" boot disk.
➜  Downloads diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *480.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                 Apple_APFS Container disk1         128.0 GB   disk0s2
   3:       Microsoft Basic Data Data                    223.0 GB   disk0s3
   4:       Microsoft Basic Data BOOTCAMP                128.9 GB   disk0s4

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +128.0 GB   disk1
                                 Physical Store disk0s2
   1:                APFS Volume MacOS                   11.3 GB    disk1s1
   2:                APFS Volume Preboot                 82.2 MB    disk1s2
   3:                APFS Volume Recovery                525.8 MB   disk1s3
   4:                APFS Volume VM                      2.1 GB     disk1s4
   5:                APFS Volume MacOS - Data            91.9 GB    disk1s5

/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *15.5 GB    disk2
   1:                 DOS_FAT_32 KRYPTONITE              15.5 GB    disk2s1`

**Comment by mayankk2308** [comment]
Thanks for the quick test.

**Comment by mayankk2308** [comment]
I tried a few times on external drives and it seems to be working ok now. Closing.
