### ISSUE TITLE
Boot Camp partition not appearing when using standalone Kryptonite

### ISSUE THREAD

**Issue by Piipperi** [mayankk2308/kryptonite#20]
I've been having some problems with Kryptonite since I reinstalled macOS. I noticed that if I use Kryptonite alone (no OCLP), Boot Camp partition does not appear in the OC boot menu, so I cannot boot to it without holding alt on boot and doing it that way. This also means System Preference's boot manager does not work (it sees the partition, but selecting it and restarting just goes back to macOS).

**Comment by mayankk2308** [comment]
Read faq on wiki.
