### ISSUE TITLE
[BUG] Booting to macOS gets stuck on Kryptonite, eGPU not even plugged in

### ISSUE THREAD

**Issue by Piipperi** [mayankk2308/kryptonite#21]
### What Mac are you using?

MacBook Pro 11,3

### What version of macOS are you using?

11.x

### Are you using OpenCore Legacy Patcher?

No

### What is your issue?

I reinstalled macOS 11.6 on my Mac yesterday, since then I have been unable to get Kryptonite working, both with and without OCLP. The booting just get stuck at the Apple logo, with OCLP on an IOCTL error `IOCTL (from pid 228) not recognzied 216 out of 379`

And with only Kryptonite, it got stuck on `Profile[0]: mode:7; desense:0; desense_level:0; chain_power_offset:0,0,0,0,`

I've tried resetting the PRAM of the Mac multiple times already, and the machine boots fine without Kryptonite (including OCLP alone, which works fine).

Also, the eGPU is not even plugged in.

### Upload Kryptonite Logs

[config.plist](https://github.com/mayankk2308/kryptonite/files/7283030/config.txt)
[opencore-2021-10-05-051959.txt](https://github.com/mayankk2308/kryptonite/files/7283034/opencore-2021-10-05-051959.txt)
[Lilu_1.5.6_20.6.txt](https://github.com/mayankk2308/kryptonite/files/7283040/Lilu_1.5.6_20.6.txt)

### Confirmation

- [X] I have uploaded the OpenCore **config.plist**.
- [X] I have uploaded all OpenCore Logs.
- [X] I have uploaded Lilu logs.
- [X] I have explained my issue in detail.

**Comment by mayankk2308** [comment]
@Piipperi please try re-creating the disk using the installer (or download manually from releases section). The `config.plist` does not exactly match the one provided as part of the `1.0.1` release. `MinKernel` and `MaxKernel` keys are missing for the kext (unsure if this breaks OC, but noting the difference). The installer script doesn't add these keys (if pressing `Y` when asked if using OC) so that needs to be fixed too.

**Comment by Piipperi** [comment]
> @Piipperi please try re-creating the disk using the installer. The `config.plist` does not exactly match the one provided as part of the `1.0.1` release. `MinKernel` and `MaxKernel` keys are missing for the kext (unsure if this breaks OC, but noting the difference). The installer script doesn't add these keys (if pressing `Y` when asked if using OC) so that needs to be fixed too.

I've tried to do that 3 times now... the booting just seems to get stuck at random things. Right now as of writing this, it's stuck on `000033.661050 Bluetooth USB Host Controller@14330000: IOUSBHostDevice::setPowerStateGated: kPowerStateSuspended -> kPowerStateOn`

**Comment by mayankk2308** [comment]
Are you sure you are erasing the disk and starting from scratch? The config you provided doesn’t indicate so.

**Comment by Piipperi** [comment]
Yes, I have done it 3 times now from scratch where I've let Kryptonite do the formatting. If the config says the drive name is OCLP, I might have renamed the drive to OCLP for that particular try.

Also I've now changed the mux manually, still no difference

**Comment by mayankk2308** [comment]
Please try without disabling dGPU.

**Comment by Piipperi** [comment]
> Please try without disabling dGPU. Also share config.plist and logs for attempt.
[config.plist](https://github.com/mayankk2308/kryptonite/files/7287757/config.txt)

Seems to work fine now.

**Comment by mayankk2308** [comment]
Booting other configurations can cause mux setting to change and as mentioned in the wiki, setting the mux doesn’t always work and you may need to retry and reboot until it does. This is not a bug with Kryptonite or OpenCore but just how Apple firmware behaves. Next time please double-check if boot works w/o disabling the discrete GPU before opening an issue.

**Comment by Piipperi** [comment]
Guess I'll just keep trying then, thanks.
