### ISSUE TITLE
[BUG] Kernel panic/sleep issues on iMac

### ISSUE THREAD

**Issue by FarFromSane** [mayankk2308/kryptonite#22]
### What Mac are you using?

iMac 27 in, late 2013 (iMAC 14,2) 

### What version of macOS are you using?

10.15.x

### Are you using OpenCore Legacy Patcher?

No

### What is your issue?

Ocasional kernel panic when booted via Kryptonite.   This will happen hours/days post boot.
Also, system will have sleep issues when on Kryptonite.   It would go to a black screen, but not wake fully.   The work-around for this is disabling system sleep.   As the 'panic' happens about the same frequency as the prior sleep issue, they may be related.    Using a Radeon 570 in a external gpu via Apple TB2-3 adapter.    I don't have Kryptonite logs, but have attached the kernel panic info.    Let me know what else you need and I'll get it.    

There are two instances of the crash in the attached file 
[iMacCrashEGPU.txt](https://github.com/mayankk2308/kryptonite/files/7360385/iMacCrashEGPUtxt)
i

### Upload Kryptonite Logs

Click here, then drag and drop your files in this area.

### Confirmation

- [X] I have uploaded the OpenCore **config.plist**.
- [X] I have uploaded all OpenCore Logs.
- [X] I have uploaded Lilu logs.
- [X] I have explained my issue in detail.

**Comment by mayankk2308** [comment]
Can’t download your panic logs. Could you please re-upload?

**Comment by FarFromSane** [comment]
Done
