### ISSUE TITLE
[BUG] Can't boot Windows from external Drive

### ISSUE THREAD

**Issue by OptiTheNext** [mayankk2308/kryptonite#23]
### What Mac are you using?

IMac Mid 2011

### What version of macOS are you using?

10.14.x

### Are you using OpenCore Legacy Patcher?

No

### What is your issue?

I installed Kryptonite on an external USB Stick and can boot MAC OSX High Sierra normally. I also have windows installed over Bootcamp, from the normal bootloader I can start it, but from the external USB I don't have the option to start Windows 8.1. I also have Misc > ScanPolicy > 0. 
Is this a bug? 
Am I doing something wrong?
Please help! 

### Upload Kryptonite Logs

[config.plist.zip](https://github.com/mayankk2308/kryptonite/files/7499640/config.plist.zip)

### Confirmation

- [X] I have uploaded the OpenCore **config.plist**.
- [X] I have uploaded all OpenCore Logs.
- [X] I have uploaded Lilu logs.
- [X] I have explained my issue in detail.

**Comment by mayankk2308** [comment]
Your Windows install needs to be UEFI and not legacy BIOS (OpenCore doesn’t support the latter), which is what old macs default to. You need to check what your install is like and convert to UEFI if needed. You can look up how to do this. If it still doesn’t work on UEFI, please see OpenCore documentation on working with Windows.
