### ISSUE TITLE
[BUG] Installation issue

### ISSUE THREAD

**Issue by j-t-chung** [mayankk2308/kryptonite#25]
### What Mac are you using?

macbook pro 8.3

### What version of macOS are you using?

12.x

### Are you using OpenCore Legacy Patcher?

Yes

### What is your issue?

Hello I apologize if this is a retarded question. but when I run the installer  script
I get this:
Invalid choice. Please try again.

Invalid choice. Please try again.

Drag and drop your OpenCore disk here. Then press RETURN.
Disk Path: / 

IS there a way I can determine what my opencore disk is?

### Upload Kryptonite Logs

Click here, then drag and drop your files in this area.

### Confirmation

- [X] I have uploaded the OpenCore **config.plist**.
- [X] I have uploaded all OpenCore Logs.
- [X] I have uploaded Lilu logs.
- [X] I have explained my issue in detail.

**Comment by mayankk2308** [comment]
https://github.com/mayankk2308/kryptonite/wiki/Create-OpenCore-Disk#using-efi-partition Probably EFI partition.
