### ISSUE TITLE
[BUG]has 16 Err in opencore stdout

### ISSUE THREAD

**Issue by LonYui** [mayankk2308/kryptonite#29]
### What Mac are you using?

macbook pro 14

### What version of macOS are you using?

11.x

### Are you using OpenCore Legacy Patcher?

Yes

### What is your issue?

env : my gpu is rx580 8g
finish installation guide
can't attach  eGPU

then i reinstall with debug mode

i fix one error when boot. fix it (changed type real to integer in plist.)
stilll can't attache eGPU
then i open the stdout of opencore
find there is 16 err in the std out

i giveup
![截圖 2022-06-12 下午7 22 49](https://user-images.githubusercontent.com/9551862/173230750-1e51cda0-93e2-42eb-a2cc-96ff7f9f6b2b.png)

### Upload Kryptonite Logs

Click here, then drag and drop your files in this area
[opencore-2022-06-12-110502.txt](https://github.com/mayankk2308/kryptonite/files/8885720/opencore-2022-06-12-110502.txt)
[Lilu_1.5.6_20.6.txt](https://github.com/mayankk2308/kryptonite/files/8885721/Lilu_1.5.6_20.6.txt)
.

### Confirmation

- [X] I have uploaded the OpenCore **config.plist**.
- [X] I have uploaded all OpenCore Logs.
- [X] I have uploaded Lilu logs.
- [X] I have explained my issue in detail.

**Comment by mayankk2308** [comment]
Don’t see anything wrong with the logs. Please clarify if this is a 13’ or 15’ Mac and what discrete gpu it has (if it does).

**Comment by LonYui** [comment]
Hi Mayans :It's Mac early 2014 13' , the discrete gpu is Iris 1536mb

Mayank Kumar ***@***.***>於 2022年6月27日 週一，上午9:57寫道：

**Comment by mayankk2308** [comment]
Support alongside OCLP is not guaranteed. There may be patches from them that can break egpus.
