### ISSUE TITLE
can't choose a disk when installing (on macOS Monterey Beta 2)

### ISSUE THREAD

**Issue by czyz** [mayankk2308/kryptonite#3]
When I enter the disk number in the ">>Available Disks" menu, this happens:

```
1
ui.sh: line 42: read: `': not a valid identifier
Invalid selection. Please retry.

```

"1." is the number next to the FAT32 partition I created to which to install kryptonite.

I get the same error when entering "11" to Refresh, or "12" to quit.

Some possibly-relevant info:

$ echo $SHELL
/bin/bash
$ uname -a
Darwin ZCZMac.local 21.0.0 Darwin Kernel Version 21.0.0: Sun Jun 20 18:43:49 PDT 2021; root:xnu-8011.0.0.121.4~2/RELEASE_X86_64 x86_64

I took a look at line 42 of ui.sh, but am not well-enough versed with bash substitutions to know what's tripping things up here:

`  read -r "${rn1?}" -p "${b}${prompt}${n} [1-${#items[@]}]: " input
`

As far as I can tell, it's not reading any of my input. I've tried different numbers, and strings that include spaces that might be interpreted as a list of inputs. Nothing seems to get through - as in this example in which I entered 3 words of garbled text:

```
kjsdf asdfasd asdfa
ui.sh: line 42: read: `': not a valid identifier
Invalid selection. Please retry.
```

**Comment by mayankk2308** [comment]
Thank you for the report. Will debug and get back to you on this one.

**Comment by sparkplug37** [comment]
On Bir Sur I also could not select a drive at this stage of the install and found if I unplugged the extra drives I was able to get past it.

**Comment by mayankk2308** [comment]
@sparkplug37 thanks for the update. It’s a minor fix I believe and not OS related. Haven’t had time to get to it but I’ll do so soon.

**Comment by ewagner12** [comment]
Hey just wanted to add my report that I'm seeing this bug as well. It seems like line 42 in ui.sh is definitely the issue as shortening it to simply
`read -r -p "${b}${prompt}${n} [1-${#items[@]}]: " input`
gets rid of the error. Not saying that's the definitive solution as I don't know what "${rn1?}" was doing?
