### ISSUE TITLE
[BUG] On mid-2011 iMac only works in High Sierra with MXM GPU Model OCLP config

### ISSUE THREAD

**Issue by rkitover** [mayankk2308/kryptonite#32]
### What Mac are you using?

iMac 12,2 -- mid 2011 -- MD063LL -- A1312

### What version of macOS are you using?

10.13.x

### Are you using OpenCore Legacy Patcher?

Yes

### What is your issue?

I have gotten Kryptonite to work on my mid-2011 iMac with a Radeon RX 570 4GB eGPU, but only in High Sierra and only when I set this option in OCLP configuration:

`Settings -> Developer Settings -> GPU Model for MXM iMacs -> AMD Polaris`

. If I do not set this option, then System Report only shows a non-functional `Display` device for my eGPU.

I was not able to test Mojave and Catalina because OCLP does not support them, and the mid-2011 iMac only supports OSes up to High Sierra without patches.

On Big Sur and Monterey my eGPU only shows up as a non-functional `Display` device regardless of the above setting in OCLP configuration.

I have attached the Lilu log from my non-functional Monterey configuration. I did not see anything interesting in it. I'm sorry I do not have the other logs because the iMac has already been reinstalled multiple times as I was trying to figure out what is the most recent OS I can run with a functional eGPU.

I'm happy to do any additional testing if you like, and maybe help out with the fixes if I can and they are possible.

### Upload Kryptonite Logs

Click here, then drag and drop your files in this area.
[Lilu_1.5.6_21.6.txt](https://github.com/mayankk2308/kryptonite/files/9333915/Lilu_1.5.6_21.6.txt)
[config.plist.gz](https://github.com/mayankk2308/kryptonite/files/9333926/config.plist.gz)

### Confirmation

- [X] I have uploaded the OpenCore **config.plist**.
- [X] I have uploaded all OpenCore Logs.
- [X] I have uploaded Lilu logs.
- [X] I have explained my issue in detail.

**Comment by rkitover** [comment]
Yesterday I noticed an unfortunate side-effect of this configuration I have for High Sierra, the "prefer eGPU" option does not show up in app infos. I was able to get the eGPU to work by using a dummy plug, making it the primary display and turning on mirroring. This is a very suboptimal configuration however and makes some things so slow as to be unusable.

Maybe because I used that OLCP config something considers my 570 a dGPU instead of an eGPU, any ideas?

**Comment by rkitover** [comment]
I found a solution, setting `GPUSelectionPolicy` to `preferRemovable` either in the app's `Info.plist` or in the preferences with `defaults write <bundle-id>` makes my eGPU work.

For Steam games it has to be set in the preferences for both the app and the helper.

**Comment by mayankk2308** [comment]
Support with OCLP is not guaranteed. In this case your Mac is too old and the workarounds needed to make your system boot newer OSes break egpu support.

**Comment by rkitover** [comment]
Also wanted to say that I got a Vega64, and it works great as an eGPU with this method in High Sierra.

Do you know specifically what the problems might be that break eGPU support in OSes later than High Sierra on this mac?
