### ISSUE TITLE
Cant create FAT32 partition in Disk Utility  

### ISSUE THREAD

**Issue by AlexanderProd** [mayankk2308/kryptonite#4]
### Problem Description

Using the Disk Utility software I can only create APFS partitions on my machine, I'm using a 2013 MacBook Pro with macOS 11.3.1 

### Screenshots

![image](https://user-images.githubusercontent.com/3080903/124742428-feb0a580-df1c-11eb-9fa9-0a46c4869fce.png)

**Comment by AlexanderProd** [comment]
I figured out I have to probably wipe the main disk, create the partition and then reinstall macOS. For now I've installed Kryptonite on a USB thumb drive and it works.

**Comment by mayankk2308** [comment]
@AlexanderProd no. You need to **partition**, not add a volume.

**Comment by AlexanderProd** [comment]
Yeah I’ve tried that too, but I can’t split the disk in multiple partitions. The + button to create a new partition is greyed out on. I’m guessing I’d have to wipe the disk first.

**Comment by mayankk2308** [comment]
@AlexanderProd if you have disk space, but Disk Utility doesn't allow partitioning, it's because of APFS snapshots. You can delete them (google it) to free up that space to allow partitioning (provided you have disk space left).

**Comment by AlexanderProd** [comment]
Oh yeah thank you that seems to be the problem, all my space is used by snapshots. 
Thank you very much!
