### ISSUE TITLE
no boot picker

### ISSUE THREAD

**Issue by RinnieX** [mayankk2308/kryptonite#7]
After it completed the download, when I restarted my computer and holding the OPT, I still didn't see my external disk on the boot picker.....

I tried manually before and it doesn't have the external disk on the boot picker neither. 

PS the app is called LULU, it's like a Firewall app.

_Originally posted by @RinnieX in https://github.com/mayankk2308/kryptonite/issues/6#issuecomment-878726817_

**Comment by mayankk2308** [comment]
No duplicates allowed.
