### ISSUE TITLE
Documentation Enhancement: KRYPTONITE MS-DOS disk size

### ISSUE THREAD

**Issue by bzaks1424** [mayankk2308/kryptonite#8]
### Feature Description
Hey team - 
I have no idea how big to make the bootloader disc for kryptonite. It would be nice if you could link to the appropriate description in the open core project for that size or offer a size necessary for bootloading with kryptonite.

**Comment by mayankk2308** [comment]
@bzaks1424 not a team, it’s just me :)

100 MB is good. I’ll update the docs soon.

**Comment by mmcdonnell-mulesoft** [comment]
Whatever supreme deity you subscribe to: bless you. That's amazing.

**Comment by mayankk2308** [comment]
@bzaks1424 documentation added.

@mmcdonnell-mulesoft :)

**Comment by tomekc** [comment]
Hi, apparently 100 MB is way to less:

```
Started erase on disk0s3 (KRYPTONITE)
Unmounting disk
Erasing
newfs_msdos: 61542 clusters too few clusters for FAT32, need 65525
4096 bytes per physical sector
```

I suggest ~256 MB partition size, or doing something wrong (Big Sur)

**Comment by mayankk2308** [comment]
Updated docs will have higher disk size recommendation (you can see the wiki pages for updated guide).
